export const CONTACT_SENT = 'CONTACT_SENT';
export const VOUCHER_PURCHASE_SUCCESSFUL = 'VOUCHER_PURCHASE_SUCCESSFUL';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const GET_ERRORS = 'GET_ERRORS'
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

